# Generated by Django 4.2 on 2025-03-27 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Zero_Product',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=50, verbose_name='제품명')),
                ('carbohydrates', models.FloatField(verbose_name='탄수화물 (g)')),
                ('protein', models.FloatField(verbose_name='단백질 (g)')),
                ('fat', models.FloatField(verbose_name='지방 (g)')),
                ('sodium', models.FloatField(verbose_name='나트륨 (mg)')),
                ('maltitol', models.FloatField(verbose_name='말티톨 (g)')),
                ('maltitol_syrup', models.FloatField(verbose_name='말티톨 시럽 (g)')),
                ('glucose_syrup', models.FloatField(verbose_name='물엿 (g)')),
            ],
            options={
                'verbose_name': '제로식품',
                'verbose_name_plural': '제로식품 목록',
            },
        ),
    ]
