# Generated by Django 4.2 on 2025-03-28 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='zero_product',
            name='Caffeine',
            field=models.FloatField(default=0, verbose_name='카페인 (g)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='Capacity',
            field=models.FloatField(default=0, verbose_name='용량 (g)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='Cholesterol',
            field=models.FloatField(default=0, verbose_name='콜레스테롤 (mg)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='GI',
            field=models.FloatField(default=0, verbose_name='GI지수'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='GL',
            field=models.FloatField(default=0, verbose_name='GL지수'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='Product_calorific_value',
            field=models.FloatField(default=0, verbose_name='열량 (g)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='Raw_materials',
            field=models.CharField(default='Unknown', max_length=255, verbose_name='원재료명'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='Sugar_alcohol',
            field=models.FloatField(default=0, verbose_name='당알콜 (g)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='product_Manufacturer',
            field=models.CharField(default='Unknown', max_length=50, verbose_name='제조사명'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='saturated_fat',
            field=models.FloatField(default=0, verbose_name='포화지방 (g)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='sugar',
            field=models.FloatField(default=0, verbose_name='당류 (g)'),
        ),
        migrations.AddField(
            model_name='zero_product',
            name='trans_fat',
            field=models.FloatField(default=0, verbose_name='트렌스지방 (g)'),
        ),
        migrations.AlterField(
            model_name='zero_product',
            name='glucose_syrup',
            field=models.FloatField(default=0, verbose_name='물엿 (g)'),
        ),
        migrations.AlterField(
            model_name='zero_product',
            name='maltitol',
            field=models.FloatField(default=0, verbose_name='말티톨 (g)'),
        ),
        migrations.AlterField(
            model_name='zero_product',
            name='maltitol_syrup',
            field=models.FloatField(default=0, verbose_name='말티톨 시럽 (g)'),
        ),
        migrations.AlterField(
            model_name='zero_product',
            name='sodium',
            field=models.FloatField(default=0, verbose_name='나트륨 (mg)'),
        ),
    ]
