# Generated by Django 4.2 on 2025-03-28 01:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Product', '0003_alter_zero_product_caffeine_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zero_product',
            old_name='product_Manufacturer',
            new_name='Manufacturer',
        ),
    ]
