# Generated by Django 4.2 on 2025-03-28 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Product', '0004_rename_product_manufacturer_zero_product_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zero_product',
            name='Capacity',
            field=models.TextField(default=0, verbose_name='용량 (g)'),
        ),
    ]
