# Generated by Django 4.2 on 2025-03-28 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Zero_Product', '0007_alter_zero_product_caffeine_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='zero_product',
            name='emoji',
            field=models.CharField(default='😊', max_length=20),
        ),
    ]
